FROM python:3.10

COPY ./requirements.cpu.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ./guidance_server/main.py main.py

# Set the entrypoint
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
